# Generated by Django 4.2.11 on 2024-10-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('emp_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('FIN', 'Finance'), ('ENG', 'Engineering'), ('MKT', 'Marketing')], max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
